---
- name: Ensure the required NuGet package provider version is installed
  ansible.windows.win_shell: Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force
  ignore_errors: true

- name: Enable Dark Mode for Apps
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize
    name: AppsUseLightTheme
    data: 0

- name: Enable Dark Mode for System
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize
    name: SystemUsesLightTheme
    data: 0

- name: Set Hidden files and folders to be shown
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: Hidden
    data: 1

- name: Show file extensions
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: HideFileExt
    data: 0

- name: Show drives with no media
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: HideDrivesWithNoMedia
    data: 0

- name: Disable sync provider notifications
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: ShowSyncProviderNotifications
    data: 0

- name: Configure TLS 1.0 settings
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols
    name: "TLS 1.0"
    state: present

- name: Configure TLS 1.0 Server settings
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
    name: Enabled
    data: 0

- name: Configure TLS 1.0 Server settings
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
    name: DisabledByDefault
    data: 1

- name: Configure TLS 1.0 Client settings
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
    name: Enabled
    data: 0

- name: Configure TLS 1.0 Client settings
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
    name: DisabledByDefault
    data: 1

- name: Create TLS 1.1 registry keys
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols
    name: TLS 1.1
    state: present

- name: Create TLS 1.1 Server registry key
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1
    name: Server
    state: present

- name: Create TLS 1.1 Client registry key
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1
    name: Client
    state: present

- name: Disable TLS 1.1 Client
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
    name: Enabled
    type: dword
    data: 0

- name: Set TLS 1.1 Client DisabledByDefault to True
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
    name: DisabledByDefault
    type: dword
    data: 1

- name: Disable TLS 1.1 Server
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
    name: Enabled
    type: dword
    data: 0

- name: Set TLS 1.1 Server DisabledByDefault to True
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
    name: DisabledByDefault
    type: dword
    data: 1

- name: Enable QuickEdit mode
  ansible.windows.win_regedit:
    path: HKCU:\Console
    name: QuickEdit
    type: dword
    data: 1

- name: Show run command in Start menu
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: Start_ShowRun
    type: dword
    data: 1

- name: Show administrative tools in Start menu
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: StartMenuAdminTools
    type: dword
    data: 1

- name: Disable network prompt
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Network\NewNetworkWindowOff

- name: Get help files for PowerShell cmdlets
  ansible.windows.win_shell: Update-Help -Force -ErrorAction Ignore
  ignore_errors: true
